### ISSUE TITLE
Unable to type however keystrokes are recorded

### ISSUE THREAD

**Issue by JoaoRuss0** [docToolchain/diagrams.net-intellij-plugin#212] opened 2023-03-25 23:49 UTC
**OS:** Ubuntu 22.10

**IntelliJCE:** Build #IC-223.8836.41, built on March 10, 2023 | Runtime version: 17.0.6+1-b653.34 amd64

As you can see the keystrokes are recorded without a problem but there is no output, I can not type anything. Clean IntelliJ installation, no setting changed or plugin installed(VIM keymap plugin is known to cause problems from what I have read on some other youtrack issues, but I do not have it enable or even have it), happens on ultimate and community on the versions below:

![Screenshot from 2023-03-25 23-52-51](https://user-images.githubusercontent.com/40304274/227747838-1a64ee9e-d65d-4efa-b657-893aa8067387.png)

![Screenshot from 2023-03-25 23-48-55](https://user-images.githubusercontent.com/40304274/227747742-d45ec463-acd7-4b66-9442-ef0aca5b2572.png)

**Comment by pawel0987** [comment] 2023-03-27 17:40
as a dirty workaround - copy-paste works :)

**Comment by ahus1** [comment] 2023-03-27 19:18
Thanks for reporting this, and sorry to hear this is causing problems for you. The lastest versions of the plugin have cause this to break on Linux (maybe other OS as well), while it works on Windows. Interaction with a mouse seems to work on all devices.

To disable the "off-screen-rendering" for this plugin, open the IDE's registry via the menu "Help | Find Action...", then search for "Registry...". The key `ide.browser.jcef.diagramsNet.osr.enabled` is enabled by default. If you disable it, and then close and open your diagram editor windows, it should then work again. 

I'll look into over the next days to see how this can be fixed without changing things in the registry.

**Comment by JoaoRuss0** [comment] 2023-03-27 20:06
@ahus1 Thank you, works like a charm after doing that :smile:

**Comment by itsjavi** [comment] 2023-03-27 20:42
@ahus1 Thanks, your solution with the registry fixed the issue for me on (PHPStorm 2022.3.3, macOS 13.2.1), also performance is much better after disabling this.

**Comment by ahus1** [comment] 2023-04-01 13:52
The plugin has now been published on the JetBrains marketplace, therefore I'm closing this issue.

**Comment by puyt** [comment] 2023-04-06 09:09
I still can't type any text unless I change the registry as suggested above.
Running plugin 0.2.2 on linux Pop!_OS 22.04. Tried reinstalling the plugin without any success.

**Comment by ahus1** [comment] 2023-04-22 07:56
Reopening this issue as the fix was probably incomplete or misleading: The intended fix was to keep the setting, but change the default of the setting, which by reading the comment wasn't successful in all cases. Also having three states here with "on", "off" and "default" is confusing.

The next iteration will remove the setting completely to allow only the setting that is known to work.

**Comment by ahus1** [comment] 2023-04-22 16:58
I managed to trace this down to https://youtrack.jetbrains.com/issue/JBR-5348

The version 0.2.3 of the plugin now disables the off-screen rendering on Linux and macOS, with no entry in the registry to change this. 

Starting with the latest IntelliJ 2023.3.1 EAP it enables it again, as not using offscreen rendering is the cause of #218.

**Closed by ahus1** 2023-04-22 16:58 UTC
Labels: bug
