### ISSUE TITLE
Lag in markdown when new version of plugin is installed

### ISSUE THREAD

**Issue by marianondrovic-alexnett** [docToolchain/diagrams.net-intellij-plugin#83] opened 2021-07-02 13:23 UTC
Since Intellij Ultimate 2021.1+ and plugin 1.7+ there is lag when you enter characters into markdown (5-15seconds). I tried to investigate why this happened but so far I see that in UI thread is open a network socket. When I use 1.5 version everything is ok, but 1.7 and 1.8 cause lag.

[threadDump-20210702-150056.txt](https://github.com/docToolchain/diagrams.net-intellij-plugin/files/6754821/threadDump-20210702-150056.txt)

**Comment by rdmueller** [comment] 2021-07-02 13:36
thanx for reporting this issue.
Where do you enter the markdown code? Within the diagrams.net editor?

**Comment by marianondrovic-alexnett** [comment] 2021-07-02 14:02
No. The interesting part is that I use bundled Markdown. We use your plugin to create diagrams, export to svg and use in *.md. But when the new plugin is installed I can enter 1 or 2 characters in markdown and have to wait 5 to 15 seconds. The issue is inside ui thread. At least I think.

**Comment by hiradyazdan** [comment] 2021-07-18 10:20
I have a similar issue, but once the draw.io plugin is enabled, the official Jetbrains markdown plugin doesn't even load anything at all and it only shows a blan white window. This at least happens on CLion, most likely on other Jetbrain's products too.

**Comment by ahus1** [comment] 2021-07-19 20:29
I've analyzed this; this is due to the SVG parsing feature I introduced for #48. If a SVG file contains an external references or a document type with a URL that resolves slowly, the UI will block. Thank you  @dylanaut for providing a SVG example.

Update plugin 0.1.9 is available from GitHub releases and will be available from the JetBrains marketplace soon after approval by the marketplace team.

**Comment by ahus1** [comment] 2021-07-19 20:34
As I was able to reproduce the problem and the fix locally, I close this issue. If the problem persists, please comment here and I'll re-open the issue.

**Closed by ahus1** 2021-07-19 20:34 UTC

**Comment by ahus1** [comment] 2021-07-20 11:42
I needed to rework this issue, as valid draw.io SVGs can contain a DTD. These files were ignored by the plugin 0.1.9. 

0.1.10 will be available soon and fix this. Builds are already running; might take 1-2 days to appear in JetBrains Marketplace.

**Comment by ahus1** [comment] 2021-07-20 11:58
Release is available from GitHub releases

**Comment by hiradyazdan** [comment] 2021-07-20 16:01
@ahus1 thanks for fixing the issue. However, I can see the 0.1.10 on Jetbrains now and updated it, but it still shows as white blank window. I've invalidated the jetbrains cache and tried again, but same..

**Comment by ahus1** [comment] 2021-07-20 17:29
@hiradyazdan - let's separate the white-preview problem to issue #87 and continue the discussion over there as it seems unrelated to this issue to me.
