### ISSUE TITLE
Cant edit text 

### ISSUE THREAD

**Issue by Lacoz** [docToolchain/diagrams.net-intellij-plugin#220] opened 2023-04-19 08:31 UTC
Trying to use the plugin within Intellij CE added text block are not editable, text is possible to focus,select and i see blinking cursor, but after pressing the key there is no change in text output.  

![Screenshot from 2023-04-19 10-28-49](https://user-images.githubusercontent.com/1428538/233016848-aa8db055-544a-4272-86ea-bdb6f426285e.png)

IntelliJ IDEA 2023.1 (Community Edition)
Build #IC-231.8109.175, built on March 28, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-67-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1980M
Cores: 8
Non-Bundled Plugins:
    de.docs_as_co.intellij.plugin.diagramsnet (0.2.2)
    name.kropp.intellij.makefile (231.8109.91)
    net.ashald.envfile (3.4.1)
    DBN (3.3.7711.0)

Kotlin: 231-1.8.20-IJ8109.175
Current Desktop: ubuntu:GNOME

**Comment by ahus1** [comment] 2023-04-22 07:57
Closing as duplicate of #212 which has now been reopened.

**Closed by ahus1** 2023-04-22 07:57 UTC
