### ISSUE TITLE
Shape data cannot be edited using keyboard

### ISSUE THREAD

**Issue by cykl** [docToolchain/diagrams.net-intellij-plugin#217] opened 2023-04-03 10:07 UTC
I'm facing a weird issue which prevent me from editing shape data using the keyboard (ex. double click on a box to edit text, double click C4 to edit its attributes).

1. Hitting a regular (ex. 'a' key no effect)
2. Backscape works as expected
3. ctrl-v & ctrl-x works as expected
4. I can move the shape using arrow key, or use ctrl-m to edit data.

Plugin used to work fine on my machine. I don't remember any 
environment change  expect upgrading  2023.1.

Screencast doesn't show the key presses but when nothing happen you can expected that I was hitting 'e'.

[Screencast from 03-04-2023 11:55:26.webm](https://user-images.githubusercontent.com/1764725/229478565-4b4f066a-a6e6-48cf-90b8-6539bc7ac3ec.webm)

IntelliJ's logs don't show any obvious error.

Environment:

* Ubuntu 22.04 (Xorg)
* IntelliJ 2023.1installed using snap
* Plugins 0.1.14, 0.2.0 and latest

**Comment by cykl** [comment] 2023-04-03 10:26
I just made a few more tests:

| Plugin version | IntelliJ version | Status |
| - | - | -| 
0.1.14 | 2022.3.3 | OK |
0.2.0 | 2022.3.3 | OK | 
0.2.2 | 2022.3.3 | KO | 
0.1.14 | 2023.1 | KO |
0.2.0 | 2023.1 | KO | 
0.2.2 | 2023.1 | KO | 

For those tests IntelliJ was installed from Jetbrain's tarballs rather than snap.

**Comment by cykl** [comment] 2023-04-03 11:00
I just discovered #212. Setting ide.browser.jcef.diagramsNet.osr.enabled to false fixed the issue, but my understanding is that it should no longer be required with 0.2.2.

I use IdeaVim but also tried to disable and it made no difference.

**Comment by ahus1** [comment] 2023-04-22 07:57
Closing as duplicate of #212 which has now been reopened.

**Closed by ahus1** 2023-04-22 07:57 UTC
