### ISSUE TITLE
high-dpi issue on Linux

### ISSUE THREAD

**Issue by psi-4ward** [docToolchain/diagrams.net-intellij-plugin#89] opened 2021-07-22 08:49 UTC
Thanks for the integration! Really useful.

But I've scaling problem with my High-DPI (4k) Setup. See the Font/Controls size difference:

![image](https://user-images.githubusercontent.com/1191572/126612642-b769725f-a472-4fb3-8c1c-b8e3453e1da2.png)

Running latest Arch-Linux with KDE on X11.

**Comment by rdmueller** [comment] 2021-07-22 09:35
interesting. diagrams.net just runs a chrome view and I do not experience these high DPI issues on my windows machine. I wonder if I could reproduce this problem with WSL...

**Comment by psi-4ward** [comment] 2021-07-22 09:42
Usually Chrome respects the GDK-3 scale settings but there is also a flag: `chromium --force-device-scale-factor=2`
Dont know if this can be forwarded to the web-view?

**Comment by ahus1** [comment] 2021-12-11 15:28
I gave it a try on a virtual machine running Fedora 35 plus IntelliJ 2020.3 and plugin version 0.1.11 - there the scaling worked. 

Could you please provide more information, but retrieving the IntelliJ and Java version you use: please open menu item "Help | About" and then use "Copy" to copy the IDE's information to the clipboard. Then paste them here. 

If you run IntelliJ, please run it with the JDK provided by JetBrains, as this fixes some HighDPI related issue.

![image](https://user-images.githubusercontent.com/3957921/145682032-d994f4e5-1e5f-4e8b-883d-3a5a9e726bdb.png)

**Comment by ahus1** [comment] 2024-02-12 22:11
Closing due to missing feedback from the creator of the issue.

**Closed by ahus1** 2024-02-12 22:11 UTC
Labels: awaiting feedback
