### ISSUE TITLE
Pressing Enter on keyboard no longer breaks the line of text in label

### ISSUE THREAD

**Issue by amstid** [docToolchain/diagrams.net-intellij-plugin#219] opened 2023-04-11 12:29 UTC
OS: Windows 11 Enterprise 22H2
IntelliJCE: IC-223.8617.56
AsciiDoc: 0.38.12
Diagrams.net Integration: 0.2.2

Love the plugin, but the latest updates seem to have changed previously understood behavior.

Previously,  due to a limitation when publishing SVG diagrams to PDF, I would manually split longer text labels by pressing Enter (to avoid a documented error in the output).

After installing 0.2.1, this no longer worked. I upgraded to 0.2.2 after seeing #217, but the issue persists. As a workaround, I found ide.browser.jcef.diagramsNet.osr.enabled and disabled it. Pressing Enter to manually split the line now works.

Not sure if this is a bug or working as intended.

Thank you.

**Comment by ahus1** [comment] 2023-04-22 07:58
Closing as duplicate of #212 which has now been reopened.

**Closed** 2023-04-22 07:58 UTC
