### ISSUE TITLE
Dark theme doesnt work

### ISSUE THREAD

**Issue by pmkyl** [docToolchain/diagrams.net-intellij-plugin#185] opened 2022-11-22 17:40 UTC
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.78-1-manjaro

Kotlin: 222-1.7.10-release-334-IJ4345.14
Current Desktop: GNOME

Basically it always shows bright theme, no matter what configuration option in selected

**Comment by damian-m-g** [comment] 2022-11-23 18:14
Reporting same issue.

RubyMine 2022.2.3
Build #RM-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 Pro x64

**Comment by belug23** [comment] 2023-01-02 14:40
It's also a problem on pycharm

PyCharm 2022.2.1 (Professional Edition)
Build #PY-222.3739.56, built on August 16, 2022
Runtime version: 17.0.3+7-b469.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

On Pop!OS 22.04

**Comment by rdmueller** [comment] 2023-01-10 21:44
Just verified it. Yes, it dooes not behave like it should :-(
I guess this was introduced through the update of diagrams.net itself.

**Comment by maxjust** [comment] 2023-01-16 12:38
Same problem on IntelliJ IDEA 2022.2.3 (Ultimate Edition)

**Comment by sjorsverhoef** [comment] 2023-02-15 20:16
Experiencing the same issue with IntelliJ IDEA 2022.3 (Ultimate Edition). Minimal, Sketch and Atlas seem to change the UI slightly but Automatic (with macbook system dark mode enabled) and Dark remain white.

**Comment by starmatf** [comment] 2023-02-20 20:28
@rdmueller Fix it, please! The dark theme doesn't work. The light theme makes my eyes suffer :)

WebStorm 2022.3.2
Build #WS-223.8617.44, built on January 24, 2023
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by ahus1** [comment] 2023-02-25 16:44
Found a documentation about the URL parameters here: https://www.diagrams.net/doc/faq/supported-url-parameters

Here might be the cause for the changes in the dark mode: Dark mode is now supported by multiple themes (but not Atlas). See https://www.diagrams.net/blog/dark-mode-diagram-editor

I'll update this issue once a pre-release is available.

**Comment by ahus1** [comment] 2023-02-25 17:16
There is now a pre-release 0.2.1 of this plugin which includes a separate configuration for the mode (dark vs. light):

![image](https://user-images.githubusercontent.com/3957921/221370510-46792488-dbc1-4022-8529-86c103933f41.png)

Please give it a try if it works for you as expected.

The pre-release of the plugin is available from [GitHub releases](https://github.com/docToolchain/diagrams.net-intellij-plugin/releases). 

To try out a pre-release:

1. Download the new release file `diagrams.net-intellij-plugin-xx.xx.xx.zip` from the _Assets_ section of the release.
2. Go to menu **File | Settings... | Plugins | Gear Icon** (⛭).
3. Choose **Install plugin from disk...**.
4. Choose the downloaded file in the file selection dialogue.
5. Restart the IDE to activate the new plugin version.

**Comment by jboehler** [comment] 2023-03-01 14:43
@ahus1 
the pre-release works on my MacBook Pro macOS 13.0.1 (22A400) in IntelliJ IDEA 2022.3.2.
Thanks a lot!

**Comment by ahus1** [comment] 2023-03-01 19:26
Thank you for testing this! I'm now closing this issue. I'll eventually promote this to a regular release. I'll wait a bit more for feedback on this and other issues that were included in that release.

**Closed by ahus1** 2023-03-01 19:26 UTC
Labels: bug, awaiting feedback

**Comment by damian-m-g** [comment] 2023-03-11 01:02
Sir, this looks fixed, thank you very much!
