### ISSUE TITLE
Keybindings not working properly All IntelliJ 2022.3.3

### ISSUE THREAD

**Issue by KhanMechAI** [docToolchain/diagrams.net-intellij-plugin#209] opened 2023-03-15 23:17 UTC
Hey team,

The plugin seems to have broken with all IntelliJ products on 2022.3.3. I've had trouble with `delete`, `command+z`, `command+c` and `command+v`, but its probably far more.

It works when i create from scratch and start typing. But as soon as I need to delete, copy or paste these functions seem to not be working.

Tested in GoLand and CLion (can test in the rest of the intellij stack too, but i assume its going to be the same for all of them)

**Comment by itsjavi** [comment] 2023-03-22 13:24
I can confirm that this also happens for PHPStorm and Webstorm (v2022.3.3 , not sure about early versions)

**Comment by ahus1** [comment] 2023-03-27 19:38
This might be a duplicate of #212 - please see there fore more details. Which operating system are you using?

**Comment by kneisslm** [comment] 2023-03-28 05:49
The solution [described in #212 ](https://github.com/docToolchain/diagrams.net-intellij-plugin/issues/212#issuecomment-1485734058) works for me.

**Comment by ahus1** [comment] 2023-03-29 07:35
Closing this as a duplicate of #212 with the previous comment. 

Please follow the other issue for updates.

**Closed by ahus1** 2023-03-29 07:35 UTC
Labels: awaiting feedback
